### ISSUE TITLE
Can you please make the Minutes and MBs to check a ENV variable for the Docker container?

### ISSUE THREAD

**Issue by roelbroersma** [lodu/TMobile-NL-Unlimited-Bundle-Automated#4]
Example: The 4G voor Thuis Extra Snel package is abou 100Mbit. When users are downloading it's possible to download about >3000MB within 5 minutes... so the default check for <2000MB which happens every 5 minutes might not be enough...

**Comment by lodu** [comment]
Sorry for the late reaction, didn't receive a notification. Good idea: I'll get right on it!

**Comment by lodu** [comment]
Added with merge of PR: https://github.com/lodu/TMobile-NL-Unlimited-Bundle-Automated/pull/5 ✅

**Comment by roelbroersma** [comment]
Hi Lodu,



(I think you speak Dutch)


Your docker image doesn't have a 'latest' branch,  so it's impossible to 
download on (for example) an Synology NAS.




PS.  Thank for adding the environment variables,.. but what's their name?  I 
don't see them documentated..?


Kind regards,



Roel Broersma


From: lodu ***@***.***>
To: lodu/TMobile-NL-Unlimited-Bundle-Automated 
***@***.***>
Cc: Roel Broersma ***@***.***>,  Author ***@***.***>
Date: Sun, 18 Sep 2022 08:12:48 -0700
Subject: Re: [lodu/TMobile-NL-Unlimited-Bundle-Automated] Can you please 
make the Minutes and MBs to check a ENV variable for the Docker container? 
(Issue #4)






Sorry for the late reaction, didn't receive a notification. Good idea: I'll 
get right on it!

**Comment by lodu** [comment]
Env is `UPDATE_INTERVAL` (see README.md).

> Your docker image doesn't have a 'latest' branch,  so it's impossible to
download on (for example) an Synology NAS.

is there no way to use "main" in stead of "latest"? (I don't use Synology NAS so wouldn't know)

**Comment by Mattie112** [comment]
It has been some years since I was running synology but I am 100% sure you could run tags. I often build my own containers (with tags like `dev` etc) and that was working.

I found this screenshot for example:
![image](https://user-images.githubusercontent.com/662896/193326575-ffbfe7e3-a29c-4689-bb9d-cb94b7a27323.png)
https://linuxhint.com/run-docker-containers-synology-nas/

Does that help?

**Comment by roelbroersma** [comment]
I mean that is has no default tag for download.  See this:










And then you got this:








~ Roel


From: Matthijs ***@***.***>
To: lodu/TMobile-NL-Unlimited-Bundle-Automated 
***@***.***>
Cc: Roel Broersma ***@***.***>,  Author ***@***.***>
Date: Fri, 30 Sep 2022 10:41:50 -0700
Subject: Re: [lodu/TMobile-NL-Unlimited-Bundle-Automated] Can you please 
make the Minutes and MBs to check a ENV variable for the Docker container? 
(Issue #4)






It has been some years since I was running synology but I am 100% sure you 
could run tags. I often build my own containers (with tags like dev etc) and 
that was working.

I found this screenshot for example:

https://linuxhint.com/run-docker-containers-synology-nas/

Does that help?

**Comment by roelbroersma** [comment]
When you look at this URL:   
https://registry.hub.docker.com/r/lodu/unlimited-sim-automation


You see that the docker image has not tags.






From: Matthijs ***@***.***>
To: lodu/TMobile-NL-Unlimited-Bundle-Automated 
***@***.***>
Cc: Roel Broersma ***@***.***>,  Author ***@***.***>
Date: Fri, 30 Sep 2022 10:41:50 -0700
Subject: Re: [lodu/TMobile-NL-Unlimited-Bundle-Automated] Can you please 
make the Minutes and MBs to check a ENV variable for the Docker container? 
(Issue #4)






It has been some years since I was running synology but I am 100% sure you 
could run tags. I often build my own containers (with tags like dev etc) and 
that was working.

I found this screenshot for example:

https://linuxhint.com/run-docker-containers-synology-nas/

Does that help?

**Comment by Mattie112** [comment]
I think you should use:

ghcr.io/lodu/tmobile-nl-unlimited-bundle-automated:main

(at least that is listed in the docs)

**Comment by lodu** [comment]
As @Mattie112 noticed, Its not using the Docker Hub Registry (I'm not even sure how you ended up there, please tell me if its linked somewhere in this repo) but Github's owns container registry ([ghcr.io](https://ghcr.io)).
This is due to me using a default template build/publish action ([see here](https://github.com/lodu/TMobile-NL-Unlimited-Bundle-Automated/blob/main/.github/workflows/docker-publish.yml), which I'll look into in the future :)).


So try using `ghcr.io/lodu/tmobile-nl-unlimited-bundle-automated` as the image/container and `main` as the tag.

**Comment by roelbroersma** [comment]
Well,


ghcr.io can't be added into Synology via the GUI.  It gives a register 
error.  There are many reports about this on the internet.   The default 
registry for Docker on Synology is DockerHub 
(https://registry.hub.docker.com)  And if you do a search in there for lodu 
or tmobile unlimited.  You find this package, that's how I came there.


Kind regards,



Roel Broersma


From: lodu ***@***.***>
To: lodu/TMobile-NL-Unlimited-Bundle-Automated 
***@***.***>
Cc: Roel Broersma ***@***.***>,  Author ***@***.***>
Date: Sat, 01 Oct 2022 10:23:21 -0700
Subject: Re: [lodu/TMobile-NL-Unlimited-Bundle-Automated] Can you please 
make the Minutes and MBs to check a ENV variable for the Docker container? 
(Issue #4)






As @Mattie112 noticed, Its not using the Docker Hub Registry (I'm not even 
sure how you ended up there, please tell me if its linked somewhere in this 
repo) but Github's owns container registry (ghcr.io).
This is due to me using a template build/publish action (see here, which I 
have not changed yet (which I'll look into in the future :)).

So try using ghcr.io/lodu/tmobile-nl-unlimited-bundle-automated as the 
image/container and main as the tag.

**Comment by roelbroersma** [comment]
See: 
https://www.reddit.com/r/synology/comments/wtkyrx/has_anyone_successfully_added_github_packages/




From: lodu ***@***.***>
To: lodu/TMobile-NL-Unlimited-Bundle-Automated 
***@***.***>
Cc: Roel Broersma ***@***.***>,  Author ***@***.***>
Date: Sat, 01 Oct 2022 10:23:21 -0700
Subject: Re: [lodu/TMobile-NL-Unlimited-Bundle-Automated] Can you please 
make the Minutes and MBs to check a ENV variable for the Docker container? 
(Issue #4)






As @Mattie112 noticed, Its not using the Docker Hub Registry (I'm not even 
sure how you ended up there, please tell me if its linked somewhere in this 
repo) but Github's owns container registry (ghcr.io).
This is due to me using a template build/publish action (see here, which I 
have not changed yet (which I'll look into in the future :)).

So try using ghcr.io/lodu/tmobile-nl-unlimited-bundle-automated as the 
image/container and main as the tag.

**Comment by lodu** [comment]
So I removed the container from the Docker Hub Registry, so I am closing this issue.
